export const ROUTES = {
  home: '/',
  login: '/login',
  vendorRegister: '/login?tab=signup&role=vendor',
  categories: '/categories',
  category: (id) => `/category/${id}`,
  product: (id) => `/product/${id}`,
  vendor: (id) => `/vendor/${id}`,
  verifiedVendors: '/verified-vendors',
  cart: '/cart',
  checkout: '/checkout',
  wishlist: '/wishlist',
  messages: '/messages',
  orderConfirmation: (id) => `/order-confirmation/${id}`,
  user: { dashboard: '/user', orders: '/user/orders', profile: '/user/profile', saved: '/user/saved', messages: '/user/messages' },
  vendor: { dashboard: '/vendor', profile: '/vendor/profile', products: '/vendor/products', orders: '/vendor/orders', messages: '/vendor/messages', subscription: '/vendor/subscription', settings: '/vendor/settings' },
  admin: { dashboard: '/admin', vendors: '/admin/vendors', users: '/admin/users', reports: '/admin/reports', reviews: '/admin/reviews' },
  legal: { terms: '/legal/terms', privacy: '/legal/privacy', vendorPolicy: '/legal/vendor-policy', cookies: '/legal/cookies' },
};
